enable_audio_bell no
confirm_os_window_close 0
shell_integration no-cursor
cursor_shape block
font_size 10 
font_family monspace
cursor_trail 1

tab_bar_style custom
active_tab_foreground #000000
active_tab_background #fafafa
inactive_tab_foreground #cccccc
inactive_tab_background #424242
tab_title_template "{index}:{title}"

