#!/usr/bin/bash


# --------------
# PKG INSTALL
# --------------

# Update system
# --------------
# sudo pacman -Syu
# #sudo pacman -S --needed --noconfirm $(cat packages)
#
#
# # --------------
# # BASIC CONFIG
# # --------------
# cd ~
# mkdir dow dox pix vid mnt opt dev 
# mkdir ~/.local/bin
# mkdir ~/.local/share/fonts
# mkdir ~/.local/share/icons
# mkdir ~/.local/share/themes
#
# # --------------
# # SERVICES
# # --------------
#
#
#
# # --------------
# # SYMLINKS
# # --------------
ln -s --force ~/dev/dots/nvim/ ~/.config/
ln -s --force ~/dev/dots/tmux/ ~/.config/
ln -s --force ~/dev/dots/qtile/ ~/.config/
ln -s --force ~/dev/dots/emacs/ ~/.config/
ln -s --force ~/dev/dots/.xinitrc ~/
ln -s --force ~/dev/dots/.bashrc ~/
ln -s --force ~/dev/dots/.gitconfig ~/

ln -s --force ~/dev/dots/misc/dunst/ ~/.config/
ln -s --force ~/dev/dots/misc/mimeapps.list ~/.config/
ln -s --force ~/dev/dots/misc/user-dirs.dirs  ~/.config/
ln -s --force ~/dev/dots/misc/fontconfig/ ~/.config/
ln -s --force ~/dev/dots/misc/gtk-3.0/ ~/.config/
ln -s --force ~/dev/dots/misc/picom/ ~/.config/

ln -s --force ~/dev/dots/bin/setbg ~/.local/bin/
ln -s --force ~/dev/dots/bin/shot ~/.local/bin/
ln -s --force ~/dev/dots/bin/tmuxer ~/.local/bin/
ln -s --force ~/dev/dots/bin/autostart ~/.local/bin/
ln -s --force ~/dev/dots/bin/launcher ~/.local/bin/
ln -s --force ~/dev/dots/bin/pf ~/.local/bin/

