
# Smooth transition
vsync = true;
backend = "glx";
shadow = false;

# Fade
fading = false;
fade-in-step = 0.1;
fade-out-step = 0.1;

# Transparency / Opacity 
active-opacity = 1.0;
inactive-opacity = 1.0;
opacity-rule = [
    "100:window_type = 'utility'",
];



